### ISSUE TITLE
Erro ao notificar por email

### ISSUE THREAD

**Issue by georgemaia** [georgemaia/sgce#1]
![erro envio email](https://user-images.githubusercontent.com/8619309/78404081-0c69d380-75d4-11ea-84d1-46709309608b.png)

**Comment by georgemaia** [comment]
Mensagem no log:

ERROR - 2020-04-04 10:59:56 --> Severity: Warning  --> fsockopen(): unable to connect to gmail-smtp-in.l.google.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 10:59:59 --> Severity: Warning  --> fsockopen(): unable to connect to alt1.gmail-smtp-in.l.google.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:02 --> Severity: Warning  --> fsockopen(): unable to connect to alt2.gmail-smtp-in.l.google.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:05 --> Severity: Warning  --> fsockopen(): unable to connect to alt3.gmail-smtp-in.l.google.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:08 --> Severity: Warning  --> fsockopen(): unable to connect to alt4.gmail-smtp-in.l.google.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:11 --> Severity: Warning  --> fsockopen(): unable to connect to gmail.com:25 (Connection timed out) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:11 --> Severity: Warning  --> fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:11 --> Severity: Warning  --> fsockopen(): unable to connect to g:25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) /var/www/html/sgce/system/application/libraries/Valida_email.php 180
ERROR - 2020-04-04 11:00:11 --> Severity: Notice  --> Undefined index: georgemaia@gmail.com /var/www/html/sgce/system/application/libraries/Gerenciador_de_email.php 88

**Comment by georgemaia** [comment]
Alterar o método padrão de envio de email para o sendmail

http://researchhubs.com/post/computing/linux-basic/enable-php-mail-function-to-work-on-ubuntu.html

no arquivo de configuração troquei o protocolo 'smtp' por  sendmail

**Comment by arthurandradef** [comment]
Me salvou, muito obrigado!

> Alterar o método padrão de envio de email para o sendmail
> 
> http://researchhubs.com/post/computing/linux-basic/enable-php-mail-function-to-work-on-ubuntu.html
> 
> no arquivo de configuração troquei o protocolo 'smtp' por sendmail
