### ISSUE TITLE
NOME_EVENTO não está sendo mostrado no certificado

### ISSUE THREAD

**Issue by Brackmann** [georgemaia/sgce#2]
Ao emitir um certificado a constante NOME_EVENTO não é mostrada no certificado: https://imgur.com/a/nVaV9hs
Não estou conseguindo resolver. Existe uma versão atualizada do SGCE?

**Comment by georgemaia** [comment]
A versão atual (1.0.3) não é atualizada a 5 anos :(

Talvez entrando em contato com a DTIC da Unipampa tenha alguma versão atualizada: https://sites.unipampa.edu.br/dtic/dsi/contato/
